def brazilian_serie_a_champions
  [
    { year: 2023, champion_key: "palmeiras", vice_key: "gremio" },
    { year: 2022, champion_key: "palmeiras", vice_key: "internacional" },
    { year: 2021, champion_key: "atletico_mg", vice_key: "flamengo" },
    { year: 2020, champion_key: "flamengo", vice_key: "internacional" },
    { year: 2019, champion_key: "flamengo", vice_key: "santos" },
    { year: 2018, champion_key: "palmeiras", vice_key: "flamengo" },
    { year: 2017, champion_key: "corinthians", vice_key: "palmeiras" },
    { year: 2016, champion_key: "palmeiras", vice_key: "santos" },
    { year: 2015, champion_key: "corinthians", vice_key: "atletico_mg" },
    { year: 2014, champion_key: "cruzeiro", vice_key: "sao_paulo" },
    { year: 2013, champion_key: "cruzeiro", vice_key: "gremio" },
    { year: 2012, champion_key: "fluminense", vice_key: "atletico_mg" },
    { year: 2011, champion_key: "corinthians", vice_key: "vasco" },
    { year: 2010, champion_key: "fluminense", vice_key: "cruzeiro" },
    { year: 2009, champion_key: "flamengo", vice_key: "internacional" },
    { year: 2008, champion_key: "sao_paulo", vice_key: "gremio" },
    { year: 2007, champion_key: "sao_paulo", vice_key: "santos" },
    { year: 2006, champion_key: "sao_paulo", vice_key: "internacional" },
    { year: 2005, champion_key: "corinthians", vice_key: "internacional" },
    { year: 2004, champion_key: "santos", vice_key: "athletico_pr" },
    { year: 2003, champion_key: "cruzeiro", vice_key: "santos" },
    { year: 2002, champion_key: "santos", vice_key: "corinthians" },
    { year: 2001, champion_key: "athletico_pr", vice_key: "sao_caetano" },
    { year: 2000, champion_key: "vasco", vice_key: "sao_caetano" },
    { year: 1999, champion_key: "corinthians", vice_key: "atletico_mg" },
    { year: 1998, champion_key: "corinthians", vice_key: "cruzeiro" },
    { year: 1997, champion_key: "vasco", vice_key: "palmeiras" },
    { year: 1996, champion_key: "gremio", vice_key: "portuguesa" },
    { year: 1995, champion_key: "botafogo", vice_key: "santos" },
    { year: 1994, champion_key: "palmeiras", vice_key: "corinthians" },
    { year: 1993, champion_key: "palmeiras", vice_key: "vitoria" },
    { year: 1992, champion_key: "flamengo", vice_key: "botafogo" },
    { year: 1991, champion_key: "sao_paulo", vice_key: "bragantino" },
    { year: 1990, champion_key: "corinthians", vice_key: "sao_paulo " },
    { year: 1989, champion_key: "vasco", vice_key: "sao_paulo" },
    { year: 1988, champion_key: "bahia", vice_key: "internacional" },
    { year: 1987, champion_key: "sport", vice_key: "guarani" },
    { year: 1986, champion_key: "sao_paulo", vice_key: "guarani" },
    { year: 1985, champion_key: "coritiba", vice_key: "bangu" },
    { year: 1984, champion_key: "fluminense", vice_key: "vasco" },
    { year: 1983, champion_key: "flamengo", vice_key: "santos" },
    { year: 1982, champion_key: "flamengo", vice_key: "gremio" },
    { year: 1981, champion_key: "gremio", vice_key: "sao_paulo" },
    { year: 1980, champion_key: "flamengo", vice_key: "atletico_mg" },
    { year: 1979, champion_key: "internacional", vice_key: "vasco" },
    { year: 1978, champion_key: "guarani", vice_key: "palmeiras" },
    { year: 1977, champion_key: "sao_paulo", vice_key: "atletico_mg" },
    { year: 1976, champion_key: "internacional", vice_key: "corinthians" },
    { year: 1975, champion_key: "internacional", vice_key: "cruzeiro" },
    { year: 1974, champion_key: "vasco", vice_key: "cruzeiro" },
    { year: 1973, champion_key: "palmeiras", vice_key: "sao_paulo" },
    { year: 1972, champion_key: "palmeiras", vice_key: "botafogo" },
    { year: 1971, champion_key: "atletico_mg", vice_key: "sao_paulo" },
    { year: 1970, champion_key: "fluminense", vice_key: "palmeiras" },
    { year: 1969, champion_key: "palmeiras", vice_key: "cruzeiro" },
    { year: 1968, champion_key: "botafogo", vice_key: "fortaleza" },
    { year: 1967, champion_key: "palmeiras", vice_key: "internacional" },
    { year: 1966, champion_key: "cruzeiro", vice_key: "santos" },
    { year: 1965, champion_key: "santos", vice_key: "vasco" },
    { year: 1964, champion_key: "santos", vice_key: "flamengo" },
    { year: 1963, champion_key: "santos", vice_key: "bahia" },
    { year: 1962, champion_key: "santos", vice_key: "botafogo" },
    { year: 1961, champion_key: "santos", vice_key: "bahia" },
    { year: 1960, champion_key: "palmeiras", vice_key: "fortaleza" },
    { year: 1959, champion_key: "bahia", vice_key: "santos" },
  ]
end

def seed_serie_a_champions
  p 'Seeding Brazilian Serie A Champions'
  brazilian_serie_a_champions.each do |champion|
    BrazilianSerieAChampion.find_or_create_by!(year: champion[:year]) do |brazilian_serie_a_champion|
      brazilian_serie_a_champion.champion_key = champion[:champion_key]
      brazilian_serie_a_champion.vice_key = champion[:vice_key]
    end
  end
end
